import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import AuthForm from "@/components/authform/AuthForm";
import SignInContextProvider from "@/contexts/SignInContext";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${poppins.variable} antialiased text-neutral-900 scroll-pt-20 lg:scroll-pt-32`}>
      <body>
        <SignInContextProvider>
          <Header />
          <main>{children}</main>
          <Footer />
          <AuthForm />
        </SignInContextProvider>
      </body>
    </html>
  );
}
